Load data

```{r load data}
path = "~/code/blish_pregnancy/data/P04/"
cm.list = paste0(path, list.files(pattern = "*.matrices.rds", path = path))
cm.files <- lapply(cm.list, readRDS)
names(cm.files) <- sub("\\_cell.counts.matrices.rds", "", list.files(pattern = "*.matrices.rds", path = path))
```

pre-processing

```{r pre-process}
cm.pp <- mapply(EpicPreHS, cm.files, orig.ident = names(cm.files), SIMPLIFY = F)
```

Merge
```{r merge}
preg_combined.emat <- mergeCM(cm.pp, type = "emat")
preg_combined.nmat <- mergeCM(cm.pp, type = "nmat")
dim(preg_combined.emat)
#saveRDS(preg_combined.emat, "~/code/blish_pregnancy/output/preg_combined.emat.rds")
```


##Make Seurat object
```{r}
preg_combined <- CreateSeuratObject(counts = preg_combined.emat, min.cells = 10, names.field = 1, names.delim = "\\.")
preg_combined <- PercentageFeatureSet(preg_combined, pattern = "^MT-", col.name = "percent.mt")
preg_combined <- PercentageFeatureSet(preg_combined, pattern = "^RPS", col.name = "percent.rps")
preg_combined <- PercentageFeatureSet(preg_combined, pattern = "^RPL", col.name = "percent.rpl")
preg_combined <- PercentageFeatureSet(preg_combined, pattern = "^RNA\\d8S5", col.name = "percent.rrna")
preg_combined <- SCTransform(preg_combined, vars.to.regress = c("percent.mt", "percent.rps", "percent.rpl", "percent.rrna", "nCount_RNA", "nFeature_RNA"), verbose = FALSE, return.only.var.genes = TRUE)


preg_combined <- RunPCA(preg_combined, verbose = FALSE)
preg_combined <- RunUMAP(preg_combined, dims = 1:50, verbose = FALSE)
preg_combined <- FindNeighbors(preg_combined, dims = 1:50, verbose = FALSE)
preg_combined <- FindClusters(preg_combined, resolution = 1, verbose = FALSE)

#saveRDS(preg_combined, "~/code/blish_pregnancy/output/preg_combined_04.rds")
p0 = DimPlot(preg_combined, label = TRUE) + NoLegend()

```




```{r mapping batch}
#https://satijalab.org/seurat/v3.0/interaction_vignette.html
workingobject = preg_combined
metadata = read.csv("~/code/blish_pregnancy/analysis/metadata.csv")
batchData = read.csv("~/code/blish_pregnancy/metadata/samples_2.csv")
mergedData = workingobject$orig.ident
mergedData = merge(mergedData, batchData, by.y = c("x"))
#View(mergedData)
dim(mergedData) #48192
unique(workingobject$orig.ident)
workingobject$timepoint = mergedData$timepoint #todo #done here
#View(workingobject$batch)

p1 <- DimPlot(workingobject, reduction = "umap", group.by = "timepoint")
p1$layers[[1]]$aes_params$alpha = .2 #manually sets alpha to 0.3
p1 = p1 + guides(colour = guide_legend(override.aes = list(alpha = 1,size=4))) # forces the legend to be alpha = 1


uniqueSamples = unique(workingobject$orig.ident)


```


DEGS between groups
```{r}
levels(workingobject$timepoint) = c("None","Pre", "One", "Two", "Three", "Post" )
DimPlot(workingobject, reduction = "umap", split.by = "timepoint")

```
```{r}
plots <- VlnPlot(workingobject, features = c("LYZ", "ISG15", "CXCL10"), split.by = "timepoint", group.by = "seurat_clusters", 
    pt.size = 0, combine = FALSE)
plots


```

```{r}
FeaturePlot(workingobject, features = c("CD3D", "SELL", "CREM", "CD8A", "GNLY", "CD79A", "FCGR3A", 
    "CCL2", "PPBP"), min.cutoff = "q9")

```



```{r changing alpha}
FeaturePlot(workingobject, features = c("MS4A1", "GNLY", "CD3E", "CD14", "FCER1A", "FCGR3A", "LYZ", "PPBP", 
    "CD8A"))

```





```{r}
workingobject.markers <- FindAllMarkers(workingobject, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
workingobject.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_logFC)


```